const express = require("express")
const { UserSignupController, UserLoginController, GetUserController, authorize, updatePasswordController, forgotPasswordController, isLogin, Logout, updateUserRoleToHostController, VerifyEmailController, refreshTokenController } = require("../controllers/UserController")
const UserRouter = express.Router()

UserRouter.post("/signup", UserSignupController)
UserRouter.post("/verify_email", VerifyEmailController)
UserRouter.post("/login_signin", UserLoginController)
UserRouter.post("/", authorize, GetUserController)
UserRouter.post("/change_password", updatePasswordController)
UserRouter.post("/forgot_password", forgotPasswordController)
UserRouter.post("/logout", Logout)
UserRouter.post("/isLogin", isLogin)
UserRouter.patch("/hostRole", updateUserRoleToHostController)
UserRouter.post("/refresh-token", refreshTokenController)
module.exports = UserRouter